# Generated by Django 4.2.2 on 2024-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(default='start', max_length=20),
        ),
        migrations.AlterField(
            model_name='epic',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='todo', max_length=30),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default='2003-04-25'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_goal',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default='2003-04-25'),
        ),
    ]
