# Generated by Django 4.2.2 on 2024-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_sprint_status_alter_epic_end_date_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='sprintName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
