# Generated by Django 4.2.2 on 2024-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_alter_issue_issuename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
