# Generated by Django 4.2.2 on 2024-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0007_alter_issue_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(default='', max_length=30),
        ),
    ]
