# Generated by Django 4.0.3 on 2024-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0010_epic_priority_epic_storypoint_issue_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='sprintName',
            field=models.CharField(default='', max_length=20, null=True, unique=True),
        ),
    ]
