# Generated by Django 4.0.3 on 2024-06-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0011_alter_sprint_sprintname'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_letter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
