# Generated by Django 4.0.3 on 2024-06-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0012_useraccount_color_useraccount_first_letter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_active',
            new_name='is_student',
        ),
    ]
