# Generated by Django 4.0.3 on 2024-06-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0013_rename_is_active_useraccount_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='To-Do', max_length=30),
        ),
    ]
