# Generated by Django 4.0.3 on 2024-06-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0014_alter_issue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_student',
            new_name='is_active',
        ),
    ]
