from django.urls import path
from .views import *

urlpatterns = [
   path('create/', create_project, name='create_project'),
    path('add/', add_issue, name='add_issue'),
    path('generate_invitation_token/',  generate_invitation_token, name='generate_invitation_token'),
    path('verify_invitation_token/',verify_invitation_token, name='verify_invitation_token'),
    path('process_invitation_token/',process_invitation_token, name='process_invitation_token'),
    path('project_list/',project_list, name='project_list'),
    path('issues/', ReactViews, name='project-issues'),
    path('create_issue/', create_issue, name='create_issue'),
    path('create_epic/', create_epic, name= 'create_epic'),
    path('create_sprint/', create_sprint, name= 'create_sprint'),
    path('update_sprintName/', update_sprintName, name= 'update_sprintName'),
    path('countsprints/', countsprints, name= 'update_sprintName'),
    path('issuesOfSprint/', issuesOfSprint, name= 'issuesOfSprint'),
    path('update_issueStatus/', update_issueStatus, name= 'update_issueStatus'),
    path('update_issueSprint/', update_issueSprint, name= 'update_issueSprint'),
    path('updateSprintStatus/',updateSprintStatus, name= 'updateSprintStatus'),
    path('delete_sprint/', delete_sprint, name= 'delete_sprint'),
    path('get_team_members/', get_team_members, name="get_team_members"),
    path('get_sprints/', get_sprints, name="get_sprints"),
    path('get_epics/', get_epics, name="get_epics"),
    path('get_activesprints/', get_activesprints, name="get_sprints"),
    # path('project_dropdown_data/',update_sprintName update_issueassignee/ project_dropdown_data, name="project_dropdown_data" ),
    path('csrf_token/', csrf_token, name='csrf_token'),  
    path('create_issue/', create_issue, name='create_issue'),
    path('filters_function/', filters_function, name='filters_function'),
    path('update_issue/', update_issue, name='update_issue'),
    path('delete_issue/', delete_issue, name= 'delete_issue'),
    path('update_issue_name/', update_issue_name, name= 'update_issue_name'),
    path('update_issueassignee/', update_issueassignee, name= 'update_issueassignee'),
    path('create_comment/', create_comment, name='create_comment'),
    path('fetch_comments/<str:issue_id>/', fetch_comments, name='fetch_comments'),
    path('edit_comment/', edit_comment, name='edit_comment'), 
    path('sprints/', gantt_chart_data, name='get_sprints'),
    path('project/<str:project_id>/issue_statistics/', project_issue_statistics, name='project_issue_statistics'),
    path('team_lead/<str:projectid>', get_team_lead, name='get_team_lead'),
    path('get_user_details/', get_user_details, name='get_user_details'),
    path('fetch_assignee_color/', fetch_assignee_color, name='fetch_assignee_color'),
    path('get_user_profile/', get_user_profile, name='get_user_profile'),
    path('get_assignee/', get_assignee, name='get_assignee'),
]
